#!/bin/bash
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
    echo "🚫  Commits on 'main' branch are not allowed!"
    echo "👉  Please create a new branch and open a pull request to main."
    exit 1
fi